when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: ['.crow/*', 'Cargo.toml', 'Cargo.lock', '**/*.rs']
  - event: pull_request
  - event: tag
    ref: ref/tags/v*
  - event: manual

labels:
  platform: linux/amd64

steps:
  - name: check
    image: rust:trixie
    commands:
      - apt-get update
      - apt-get install -y protobuf-compiler musl-tools
      - ln -sf /usr/bin/musl-gcc /usr/local/bin/x86_64-unknown-linux-musl-gcc
      - rustup target add x86_64-unknown-linux-musl
      - cargo check --target x86_64-unknown-linux-musl --verbose
    when:
      - event: [push, pull_request]
        path: ['.crow/*', 'Cargo.toml', 'Cargo.lock', '**/*.rs']

  - name: build
    image: rust:trixie
    commands:
      - apt-get update
      - apt-get install -y protobuf-compiler musl-tools
      - ln -sf /usr/bin/musl-gcc /usr/local/bin/x86_64-unknown-linux-musl-gcc
      - rustup target add x86_64-unknown-linux-musl
      - cargo build --release --target x86_64-unknown-linux-musl --bin sophon-cli --verbose
      - mv target/x86_64-unknown-linux-musl/release/sophon-cli sophon-tools
    when:
      - event: [tag, manual]

  - name: release
    image: woodpeckerci/plugin-release
    settings:
      api_key:
        from_secret: FORGEJO_TOKEN
      files:
        - sophon-tools
      title: sophon-tools $CI_COMMIT_TAG
    when:
      - event: tag
