syntax = "proto3";

package protos;

message SophonDownloadInfo {
    repeated SophonDownloadInfoAsset assets = 1;
}

message SophonDownloadInfoAsset {
    // Path to the asset relative to the base game directory.
    string path = 1;

    // Type of the asset.
    //
    // [ 0] - file
    // [64] - directory
    uint32 type = 3;

    // Size of the entire asset in bytes.
    uint64 size = 4;

    // Hash of the asset.
    string hash_md5 = 5;

    // List of asset chunks.
    repeated SophonDownloadInfoAssetChunk chunks = 2;
}

message SophonDownloadInfoAssetChunk {
    string name = 1;

    // Offset in the asset file at which this chunk should be written.
    uint64 offset = 3;

    // Compressed chunk size in bytes.
    uint64 compressed_size = 4;

    // Hash of the compressed chunk.
    string compressed_hash_md5 = 7;

    // Decompressed chunk size in bytes.
    uint64 decompressed_size = 5;

    // Hash of the decompressed chunk.
    string decompressed_hash_md5 = 2;

    // Unknown. Another hash value?
    uint64 unspecified = 6;
}
