on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: selfhosted
    steps:
      - uses: actions/checkout@v5

      - name: Setup rust toolchain and cache
        uses: https://codeberg.org/prjunnamed/setup-rust-toolchain@f0e3fff1ca3442708aa9fb8156820eb859d80846

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install protobuf-compiler musl-tools
          sudo ln -sf /usr/bin/musl-gcc /usr/local/bin/x86_64-unknown-linux-musl-gcc

      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-musl --bin sophon-cli --verbose
          mv target/x86_64-unknown-linux-musl/release/sophon-cli target/x86_64-unknown-linux-musl/release/sophon-tools

      - name: Upload built binary to the release
        uses: https://git.michaelsasser.org/actions/upload-release-assets@v1
        with:
          assets: |
            target/x86_64-unknown-linux-musl/release/sophon-tools
          token: ${{ forge.token }}
          tag: ${{ forge.ref_name }}
