[package]
name = "sophon-lib"
version = "0.2.0"
authors = [
    "Nikita Podvirnyi <krypt0nn@vk.com>",
    "John the Cooling Fan"
]
homepage = "https://dawn.wine/dawn-winery/sophon-tools"
repository = "https://dawn.wine/dawn-winery/sophon-tools"
license = "GPL-3.0-or-later"
rust-version = "1.94.1"
edition = "2024"
publish = false

[features]
tracing = ["dep:tracing"]
vendored-hpatchz = []

default = ["tracing", "vendored-hpatchz"]

[dependencies.reqwest]
version = "0.13"
features = [
    "rustls",
    "charset",
    "http2",
    "socks",
    "system-proxy"
]
default-features = false

[dependencies]
thiserror = "2.0"
serde_json = "1.0"
tokio = { version = "1.52", features = ["rt-multi-thread"] }
prost = "0.14"
zstd = { version = "0.13" }
md-5 = "0.11"
seahash = "4.1"
hex = "0.4"

tracing = { version = "0.1", optional = true }

[build-dependencies]
prost-build = "0.14"
